export const messagesUser_1 = [
  {
    firstName: 'Ivan',
    message: 'Hi',
    type: 'text',
    date: '',
    backgroundColor: '#2e36ac',
  },
  {
    firstName: 'Sergey',
    message: 'Hey',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'how a u?',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Ivan',
    message: 'nice and u? ',
    type: 'text',
    date: '',
    backgroundColor: '#2e36ac',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
  {
    firstName: 'Sergey',
    message: 'i too',
    type: 'text',
    date: '',
    backgroundColor: '#b93e3e',
  },
];

export const userIvan = {
  backgroundColor: '#2e36ac',
  colorName: '',
  avatar: '',
  firstName: 'Ivan',
  lastName: '',
};

export const userSergey = [
  {
    backgroundColor: '#b93e3e',
    avatar: '',
    firstName: 'Sergey',
    lastName: '',
  },
];
